---
- name: Install libselinux-python
  yum: name=libselinux-python state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install python-selinux
  apt: name=python-selinux state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Set up iptables rules
  copy: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Set up iptables rules
  copy: src=iptables-save dest=/etc/default/iptables-rules
  notify: restart iptables
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
